# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170213_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='first',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='second',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
